package Vistas;

public class Vista_Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Vista_Principal
     */
    public Vista_Principal() {
        initComponents();
    }
    
    public void configuracion(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sesionDialog = new javax.swing.JDialog();
        mainlabel = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        initBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        createAccBtn = new javax.swing.JButton();
        crearAccDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txtCrearUser = new javax.swing.JTextField();
        txtCrearPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrearUser = new javax.swing.JButton();
        btnCrearCancelar = new javax.swing.JButton();
        btnCrearGestion = new javax.swing.JButton();
        panelTools = new javax.swing.JPanel();
        medicosBtn = new javax.swing.JButton();
        pacientesBtn = new javax.swing.JButton();
        ingresosBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mainDesktop = new javax.swing.JDesktopPane();
        MainMenuBar = new javax.swing.JMenuBar();
        profileMenu = new javax.swing.JMenu();
        usersMenuItem = new javax.swing.JMenuItem();
        sesionMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        openMenu = new javax.swing.JMenu();
        medicosMenuItem = new javax.swing.JMenuItem();
        pacientesMenuItem = new javax.swing.JMenuItem();
        ingresosMenuItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        dbMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        sesionDialog.setTitle("Inicio de Sesion");
        sesionDialog.setResizable(false);

        mainlabel.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        mainlabel.setText("Iniciar Sesion");

        initBtn.setText("Iniciar Sesion");

        exitBtn.setText("Salir");

        userLabel.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        userLabel.setText("Usuario:");

        passLabel.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        passLabel.setText("Contraseña:");

        createAccBtn.setText("Crear Cuenta");

        javax.swing.GroupLayout sesionDialogLayout = new javax.swing.GroupLayout(sesionDialog.getContentPane());
        sesionDialog.getContentPane().setLayout(sesionDialogLayout);
        sesionDialogLayout.setHorizontalGroup(
            sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sesionDialogLayout.createSequentialGroup()
                        .addComponent(mainlabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sesionDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userLabel)
                            .addComponent(passLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sesionDialogLayout.createSequentialGroup()
                        .addComponent(createAccBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initBtn)))
                .addContainerGap())
        );
        sesionDialogLayout.setVerticalGroup(
            sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initBtn)
                    .addComponent(exitBtn)
                    .addComponent(createAccBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        crearAccDialog.setTitle("Creacion de Usuario");
        crearAccDialog.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        jLabel3.setText("Crear usuario");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel4.setText("Usuario:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel5.setText("Contraseña:");

        btnCrearUser.setText("Crear usuario");

        btnCrearCancelar.setText("Cancelar");

        btnCrearGestion.setText("Gestionar usuarios");

        javax.swing.GroupLayout crearAccDialogLayout = new javax.swing.GroupLayout(crearAccDialog.getContentPane());
        crearAccDialog.getContentPane().setLayout(crearAccDialogLayout);
        crearAccDialogLayout.setHorizontalGroup(
            crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearAccDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearAccDialogLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearAccDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCrearUser)
                            .addComponent(txtCrearPass, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearAccDialogLayout.createSequentialGroup()
                        .addComponent(btnCrearGestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(btnCrearCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearUser)))
                .addContainerGap())
        );
        crearAccDialogLayout.setVerticalGroup(
            crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearAccDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrearPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUser)
                    .addComponent(btnCrearCancelar)
                    .addComponent(btnCrearGestion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital");
        setMinimumSize(new java.awt.Dimension(801, 692));

        panelTools.setBackground(java.awt.Color.lightGray);
        panelTools.setToolTipText("Barra de herramientas");

        medicosBtn.setText("medicos");
        medicosBtn.setToolTipText("Crea una nueva ventana de medicos");
        medicosBtn.setPreferredSize(new java.awt.Dimension(80, 27));
        medicosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosBtnActionPerformed(evt);
            }
        });

        pacientesBtn.setText("pacientes");
        pacientesBtn.setToolTipText("Crea una nueva ventana de pacientes");
        pacientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesBtnActionPerformed(evt);
            }
        });

        ingresosBtn.setText("ingresos");
        ingresosBtn.setToolTipText("Crea una nueva ventana de ingresos");
        ingresosBtn.setPreferredSize(new java.awt.Dimension(80, 27));
        ingresosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Status: ");
        jLabel1.setToolTipText("");

        statusBtn.setBackground(java.awt.Color.red);
        statusBtn.setToolTipText("Verifica la conexion con la base de datos");

        jLabel2.setText("Bienvenido:");

        jLabel6.setText("usuario aqui");
        jLabel6.setToolTipText("Usuario actual");

        javax.swing.GroupLayout panelToolsLayout = new javax.swing.GroupLayout(panelTools);
        panelTools.setLayout(panelToolsLayout);
        panelToolsLayout.setHorizontalGroup(
            panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolsLayout.createSequentialGroup()
                .addComponent(medicosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToolsLayout.createSequentialGroup()
                        .addComponent(ingresosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToolsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(statusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelToolsLayout.setVerticalGroup(
            panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToolsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panelToolsLayout.createSequentialGroup()
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(statusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)))
            .addComponent(ingresosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainDesktop.setToolTipText("Ventana Principal");
        mainDesktop.setMinimumSize(new java.awt.Dimension(800, 600));

        profileMenu.setText("Perfil");
        profileMenu.setToolTipText("Opciones sobre el perfil actual");

        usersMenuItem.setText("Gestionar Usuarios");
        usersMenuItem.setToolTipText("Gestione los usuarios registrados en su aplicacion");
        profileMenu.add(usersMenuItem);

        sesionMenuItem.setText("Cerrar Sesion");
        sesionMenuItem.setToolTipText("Cierra la sesion del usuario actual");
        profileMenu.add(sesionMenuItem);

        exitMenuItem.setText("Salir");
        exitMenuItem.setToolTipText("Salir de la aplicacion");
        profileMenu.add(exitMenuItem);

        MainMenuBar.add(profileMenu);

        openMenu.setText("Abrir");
        openMenu.setToolTipText("Abra ventanas de la aplicacion");

        medicosMenuItem.setText("Abrir Medicos");
        medicosMenuItem.setToolTipText("Crea una nueva ventana de medicos");
        openMenu.add(medicosMenuItem);

        pacientesMenuItem.setText("Abrir Pacientes");
        pacientesMenuItem.setToolTipText("Crea una nueva ventana de pacientes");
        openMenu.add(pacientesMenuItem);

        ingresosMenuItem.setText("Abrir Ingresos");
        ingresosMenuItem.setToolTipText("Crea una nueva ventana de ingresos");
        openMenu.add(ingresosMenuItem);

        MainMenuBar.add(openMenu);

        optionMenu.setText("Opciones");
        optionMenu.setToolTipText("Opciones de configuracion");

        dbMenuItem.setText("Configuracion de Base de datos");
        dbMenuItem.setToolTipText("Configure el tipo de base de datos para almacenar sus registros");
        optionMenu.add(dbMenuItem);

        MainMenuBar.add(optionMenu);

        helpMenu.setText("Ayuda");
        helpMenu.setToolTipText("Sobre la aplicacion");

        aboutMenuItem.setText("Acerca de");
        aboutMenuItem.setToolTipText("Acerca del producto");
        helpMenu.add(aboutMenuItem);

        MainMenuBar.add(helpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainDesktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTools, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Main Program");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medicosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosBtnActionPerformed
        Vista_Medicos vista_Medicos = new Vista_Medicos();
        vista_Medicos.setVisible(true);
        mainDesktop.add(vista_Medicos);
    }//GEN-LAST:event_medicosBtnActionPerformed

    private void pacientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesBtnActionPerformed
        Vista_Pacientes vista_Pacientes = new Vista_Pacientes();
        vista_Pacientes.setVisible(true);
        mainDesktop.add(vista_Pacientes);
    }//GEN-LAST:event_pacientesBtnActionPerformed

    private void ingresosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosBtnActionPerformed
        Vista_Ingresos vista_Ingresos = new Vista_Ingresos();
        vista_Ingresos.setVisible(true);
        mainDesktop.add(vista_Ingresos);
    }//GEN-LAST:event_ingresosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnCrearCancelar;
    private javax.swing.JButton btnCrearGestion;
    private javax.swing.JButton btnCrearUser;
    private javax.swing.JDialog crearAccDialog;
    private javax.swing.JButton createAccBtn;
    private javax.swing.JMenuItem dbMenuItem;
    private javax.swing.JButton exitBtn;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton ingresosBtn;
    private javax.swing.JMenuItem ingresosMenuItem;
    private javax.swing.JButton initBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JButton medicosBtn;
    private javax.swing.JMenuItem medicosMenuItem;
    private javax.swing.JMenu openMenu;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JButton pacientesBtn;
    private javax.swing.JMenuItem pacientesMenuItem;
    private javax.swing.JPanel panelTools;
    private javax.swing.JLabel passLabel;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JDialog sesionDialog;
    private javax.swing.JMenuItem sesionMenuItem;
    private javax.swing.JButton statusBtn;
    private javax.swing.JTextField txtCrearPass;
    private javax.swing.JTextField txtCrearUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel userLabel;
    private javax.swing.JMenuItem usersMenuItem;
    // End of variables declaration//GEN-END:variables
}
