package Vistas;

import Config.Fondo;
import Config.Progreso;
import Modelos.Usuario;
import Servicios.Conexion;
import Servicios.Servicios_Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Vista_Principal extends javax.swing.JFrame {
    static Vista_Principal programa;
    // para la seccion de usuarios
    private Servicios_Usuario servicio_usuario = new Servicios_Usuario();
    private Usuario acc;
    //para la seccion visual
    public InputStream simboloMedicina=this.getClass().getResourceAsStream("/images/simbolo-medicina.png");
    Runnable x = null;
    
    public Vista_Principal() {
        initComponents();
        this.configuracion();
        this.initDialogos();
        this.setExtendedState(Vista_Principal.MAXIMIZED_BOTH);
    }
    
    public void iniciarSesion(){
        sesionDialog.setVisible(false);
        JOptionPane.showMessageDialog(null, "Bienvenido "+acc.getUser());
        userLbl.setText(acc.getUser());
        this.setVisible(true);
        this.checkConnection();
    }
    
    public void initDialogos(){
        sesionDialog.setTitle("Inicio de sesion");                 
        sesionDialog.setLocation(this.centrar());
        sesionDialog.pack();
        sesionDialog.setVisible(true);
        sesionDialog.getRootPane().setDefaultButton(initBtn);
        crearAccDialog.setTitle("Crea una cuenta");
        crearAccDialog.setLocation(this.centrar());
        crearAccDialog.getRootPane().setDefaultButton(btnCrearUser);
        crearAccDialog.pack();
    }
    
    public  void cargarImagen(javax.swing.JDesktopPane jDeskp,InputStream imagen){
        try{
            BufferedImage image = ImageIO.read(imagen);
            jDeskp.setBorder(new Fondo(image));
        }
        catch (Exception e){
            System.out.println("Imagen no disponible");
        }
    }
    
    public void configuracion(){
        this.cargarImagen(mainDesktop, simboloMedicina);
    }
    
    public Point centrar(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Point p = new Point();
        int altura = pantalla.height;
        int ancho = pantalla.width;
        p.setLocation(ancho/2.5, altura/4.5);
        return p;
    }
    
    public String getGender(){
        String gender;
        if(cbGender.getSelectedIndex() == 0){
            return "hombre";
        }else{
            return "mujer";
        }
    }
    
    public void checkConnection(){
        if(Conexion.revisar()){
            statusBtn.setBackground(Color.green);
        }else{
            statusBtn.setBackground(Color.red);
        }
    }
    
    public boolean validar(){
        boolean validar;
        String usuario = txtCrearUser.getText();
        String password = txtCrearPass.getText();
        validar = (!usuario.equals("") && !password.equals(""))||(usuario.length()>50 || password.length()>50);
        return validar;
    }
    
    public boolean validarAcc(){
        boolean validar;
        String usuario = txtUser.getText();
        String password = txtPass.getText();
        validar = (!usuario.equals("") && !password.equals(""))||(usuario.length()>50 || password.length()>50);
        return validar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sesionDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        initBtn = new javax.swing.JButton();
        pBar = new javax.swing.JProgressBar();
        mainlabel = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        createAccBtn = new javax.swing.JButton();
        crearAccDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCrearUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCrearPass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnCrearUser = new javax.swing.JButton();
        btnCrearCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        adDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        panelTools = new javax.swing.JPanel();
        medicosBtn = new javax.swing.JButton();
        pacientesBtn = new javax.swing.JButton();
        ingresosBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        mainDesktop = new javax.swing.JDesktopPane();
        MainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        profileMenu = new javax.swing.JMenu();
        usersMenuItem = new javax.swing.JMenuItem();
        sesionMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        openMenu = new javax.swing.JMenu();
        medicosMenuItem = new javax.swing.JMenuItem();
        pacientesMenuItem = new javax.swing.JMenuItem();
        ingresosMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        sesionDialog.setTitle("Inicio de Sesion");
        sesionDialog.setBackground(new java.awt.Color(255, 255, 255));
        sesionDialog.setIconImage(getIconImage());
        sesionDialog.setResizable(false);
        sesionDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                sesionDialogWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farmacia.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        userLabel.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        userLabel.setText("Usuario:");

        passLabel.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        passLabel.setText("Contraseña:");

        initBtn.setBackground(new java.awt.Color(0, 102, 153));
        initBtn.setForeground(new java.awt.Color(255, 255, 255));
        initBtn.setText("Iniciar Sesion");
        initBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        initBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initBtnActionPerformed(evt);
            }
        });

        pBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(userLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(passLabel)))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUser)
                            .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(initBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainlabel.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        mainlabel.setText("Iniciar Sesion");

        exitBtn.setBackground(new java.awt.Color(0, 102, 153));
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Salir");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        createAccBtn.setBackground(new java.awt.Color(0, 102, 153));
        createAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        createAccBtn.setText("Crear Cuenta");
        createAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(mainlabel)
                                .addGap(25, 25, 25)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainlabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAccBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout sesionDialogLayout = new javax.swing.GroupLayout(sesionDialog.getContentPane());
        sesionDialog.getContentPane().setLayout(sesionDialogLayout);
        sesionDialogLayout.setHorizontalGroup(
            sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sesionDialogLayout.setVerticalGroup(
            sesionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        crearAccDialog.setTitle("Creacion de Usuario");
        crearAccDialog.setResizable(false);
        crearAccDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                crearAccDialogWindowClosing(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        jLabel3.setText("Crear usuario");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel4.setText("Usuario:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel5.setText("Contraseña:");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hombre", "mujer" }));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel6.setText("Genero:");

        btnCrearUser.setBackground(new java.awt.Color(0, 102, 153));
        btnCrearUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUser.setText("Crear usuario");
        btnCrearUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUserActionPerformed(evt);
            }
        });

        btnCrearCancelar.setBackground(new java.awt.Color(0, 102, 153));
        btnCrearCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCancelar.setText("Cancelar");
        btnCrearCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCancelarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCrearUser, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(txtCrearPass, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(btnCrearCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCrearUser))
                        .addComponent(cbGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrearUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCrearPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUser)
                    .addComponent(btnCrearCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout crearAccDialogLayout = new javax.swing.GroupLayout(crearAccDialog.getContentPane());
        crearAccDialog.getContentPane().setLayout(crearAccDialogLayout);
        crearAccDialogLayout.setHorizontalGroup(
            crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        crearAccDialogLayout.setVerticalGroup(
            crearAccDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout adDialogLayout = new javax.swing.GroupLayout(adDialog.getContentPane());
        adDialog.getContentPane().setLayout(adDialogLayout);
        adDialogLayout.setHorizontalGroup(
            adDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adDialogLayout.setVerticalGroup(
            adDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital");
        setMinimumSize(new java.awt.Dimension(801, 692));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelTools.setBackground(new java.awt.Color(0, 0, 102));
        panelTools.setForeground(new java.awt.Color(255, 255, 255));
        panelTools.setToolTipText("Barra de herramientas");

        medicosBtn.setBackground(new java.awt.Color(0, 204, 204));
        medicosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor.png"))); // NOI18N
        medicosBtn.setToolTipText("Crea una nueva ventana de medicos");
        medicosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosBtnActionPerformed(evt);
            }
        });

        pacientesBtn.setBackground(new java.awt.Color(0, 204, 204));
        pacientesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente.png"))); // NOI18N
        pacientesBtn.setToolTipText("Crea una nueva ventana de pacientes");
        pacientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesBtnActionPerformed(evt);
            }
        });

        ingresosBtn.setBackground(new java.awt.Color(0, 204, 204));
        ingresosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingreso1.png"))); // NOI18N
        ingresosBtn.setToolTipText("Crea una nueva ventana de ingresos");
        ingresosBtn.setPreferredSize(new java.awt.Dimension(80, 27));
        ingresosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status: ");
        jLabel1.setToolTipText("");

        statusBtn.setBackground(java.awt.Color.darkGray);
        statusBtn.setToolTipText("Verifica la conexion con la base de datos");
        statusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBtnActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido:");

        userLbl.setForeground(new java.awt.Color(255, 255, 255));
        userLbl.setToolTipText("Usuario actual");

        javax.swing.GroupLayout panelToolsLayout = new javax.swing.GroupLayout(panelTools);
        panelTools.setLayout(panelToolsLayout);
        panelToolsLayout.setHorizontalGroup(
            panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolsLayout.createSequentialGroup()
                .addComponent(medicosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToolsLayout.createSequentialGroup()
                        .addComponent(ingresosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLbl)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToolsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(statusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelToolsLayout.setVerticalGroup(
            panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolsLayout.createSequentialGroup()
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(statusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userLbl)))
            .addComponent(ingresosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pacientesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medicosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainDesktop.setBackground(new java.awt.Color(224, 224, 249));
        mainDesktop.setToolTipText("Ventana Principal");
        mainDesktop.setMinimumSize(null);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardiograma.png"))); // NOI18N
        jMenu1.setEnabled(false);
        jMenu1.setFocusable(false);
        MainMenuBar.add(jMenu1);

        profileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil-user.png"))); // NOI18N
        profileMenu.setText("Perfil");
        profileMenu.setToolTipText("Opciones sobre el perfil actual");

        usersMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reanudar.png"))); // NOI18N
        usersMenuItem.setText("Gestionar Usuarios");
        usersMenuItem.setToolTipText("Gestione los usuarios registrados en su aplicacion");
        usersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersMenuItemActionPerformed(evt);
            }
        });
        profileMenu.add(usersMenuItem);

        sesionMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/candado-cerrado.png"))); // NOI18N
        sesionMenuItem.setText("Cerrar Sesion");
        sesionMenuItem.setToolTipText("Cierra la sesion del usuario actual");
        sesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionMenuItemActionPerformed(evt);
            }
        });
        profileMenu.add(sesionMenuItem);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        exitMenuItem.setText("Salir");
        exitMenuItem.setToolTipText("Salir de la aplicacion");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        profileMenu.add(exitMenuItem);

        MainMenuBar.add(profileMenu);

        openMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/abrir-min.png"))); // NOI18N
        openMenu.setText("Abrir");
        openMenu.setToolTipText("Abra ventanas de la aplicacion");

        medicosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctor-min.png"))); // NOI18N
        medicosMenuItem.setText("Abrir Medicos");
        medicosMenuItem.setToolTipText("Crea una nueva ventana de medicos");
        medicosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosMenuItemActionPerformed(evt);
            }
        });
        openMenu.add(medicosMenuItem);

        pacientesMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente-min.png"))); // NOI18N
        pacientesMenuItem.setText("Abrir Pacientes");
        pacientesMenuItem.setToolTipText("Crea una nueva ventana de pacientes");
        pacientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesMenuItemActionPerformed(evt);
            }
        });
        openMenu.add(pacientesMenuItem);

        ingresosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ingresos-min.png"))); // NOI18N
        ingresosMenuItem.setText("Abrir Ingresos");
        ingresosMenuItem.setToolTipText("Crea una nueva ventana de ingresos");
        ingresosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosMenuItemActionPerformed(evt);
            }
        });
        openMenu.add(ingresosMenuItem);

        MainMenuBar.add(openMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda-min.png"))); // NOI18N
        helpMenu.setText("Ayuda");
        helpMenu.setToolTipText("Sobre la aplicacion");

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info-min.png"))); // NOI18N
        aboutMenuItem.setText("Acerca de");
        aboutMenuItem.setToolTipText("Acerca del producto");
        helpMenu.add(aboutMenuItem);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/documentacion-min.png"))); // NOI18N
        jMenuItem1.setText("Documentacion");
        helpMenu.add(jMenuItem1);

        MainMenuBar.add(helpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Main Program");

        setBounds(0, 0, 822, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void medicosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosBtnActionPerformed
        Vista_Medicos vista_Medicos = new Vista_Medicos();
        vista_Medicos.setVisible(true);
        mainDesktop.add(vista_Medicos);
    }//GEN-LAST:event_medicosBtnActionPerformed

    private void pacientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesBtnActionPerformed
        Vista_Pacientes vista_Pacientes = new Vista_Pacientes();
        vista_Pacientes.setVisible(true);
        mainDesktop.add(vista_Pacientes);
    }//GEN-LAST:event_pacientesBtnActionPerformed

    private void ingresosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosBtnActionPerformed
        Vista_Ingresos vista_Ingresos = new Vista_Ingresos();
        vista_Ingresos.setVisible(true);
        mainDesktop.add(vista_Ingresos);
    }//GEN-LAST:event_ingresosBtnActionPerformed

    private void statusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBtnActionPerformed
        this.checkConnection();
    }//GEN-LAST:event_statusBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Conexion.cerrar();
            JOptionPane.showMessageDialog(null, "Conexion Cerrada!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "A ocurrido un error!");
        }
    }//GEN-LAST:event_formWindowClosing

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void createAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtnActionPerformed
        crearAccDialog.setVisible(true);
        sesionDialog.setVisible(false);
    }//GEN-LAST:event_createAccBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void btnCrearCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCancelarActionPerformed
        crearAccDialog.setVisible(false);
        sesionDialog.setVisible(true);
    }//GEN-LAST:event_btnCrearCancelarActionPerformed

    private void btnCrearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUserActionPerformed
        if(validar()){
            Usuario user = new Usuario();
            String usuario = txtCrearUser.getText();
            String password = txtCrearPass.getText();
            String gender = getGender();
            user.setUser(usuario);
            user.setPassword(password);
            user.setGender(gender);
            try {
                servicio_usuario.create(Conexion.obtener(), user);
                crearAccDialog.setVisible(false);
                JOptionPane.showMessageDialog(null, "Se a creado el usuario con exito!");
                sesionDialog.setVisible(true);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error al conectar a la Base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            }catch(ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null, "Error clase no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campos Incompletos o Mayores a 50 caracteres");
        }
    }//GEN-LAST:event_btnCrearUserActionPerformed

    private void initBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initBtnActionPerformed
        if(validarAcc()){
            try {
                acc = servicio_usuario.getByUser(Conexion.obtener(), txtUser.getText());
                String password = txtPass.getText().toString();
                String dbPassword = acc.getPassword();
                if(password.equals(dbPassword)){
                    Progreso p = new Progreso(pBar, programa);
                    p.execute();
                    //sesionDialog.setVisible(false);
                    //JOptionPane.showMessageDialog(null, "Bienvenido "+acc.getUser());
                    //userLbl.setText(acc.getUser());
                    //this.setVisible(true);
                    //this.checkConnection();
                }else{
                    JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error al conectar a la Base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            }catch(ClassNotFoundException ex){
                JOptionPane.showMessageDialog(null, "Error clase no encontrada", "Error", JOptionPane.ERROR_MESSAGE);
            }catch(NullPointerException ex){
                JOptionPane.showMessageDialog(null, "No existe este usuario", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campos Incompletos o Mayores a 50 caracteres");
        }
    }//GEN-LAST:event_initBtnActionPerformed

    private void sesionDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_sesionDialogWindowClosing
        System.exit(0);
    }//GEN-LAST:event_sesionDialogWindowClosing

    private void crearAccDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_crearAccDialogWindowClosing
        crearAccDialog.setVisible(false);
        sesionDialog.setVisible(true);
    }//GEN-LAST:event_crearAccDialogWindowClosing

    private void sesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionMenuItemActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Seguro que desea Salir?", "Cerrar Sesion", JOptionPane.YES_NO_OPTION);
        if(a == 0){
            sesionDialog.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_sesionMenuItemActionPerformed

    private void medicosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosMenuItemActionPerformed
        Vista_Medicos vista_Medicos = new Vista_Medicos();
        vista_Medicos.setVisible(true);
        mainDesktop.add(vista_Medicos);
    }//GEN-LAST:event_medicosMenuItemActionPerformed

    private void pacientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesMenuItemActionPerformed
        Vista_Pacientes vista_Pacientes = new Vista_Pacientes();
        vista_Pacientes.setVisible(true);
        mainDesktop.add(vista_Pacientes);
    }//GEN-LAST:event_pacientesMenuItemActionPerformed

    private void ingresosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosMenuItemActionPerformed
        Vista_Ingresos vista_Ingresos = new Vista_Ingresos();
        vista_Ingresos.setVisible(true);
        mainDesktop.add(vista_Ingresos);
    }//GEN-LAST:event_ingresosMenuItemActionPerformed

    private void usersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersMenuItemActionPerformed
        Vista_Usuarios vista_Usuarios = new Vista_Usuarios(acc);
        vista_Usuarios.setVisible(true);
        mainDesktop.add(vista_Usuarios);
    }//GEN-LAST:event_usersMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                programa = new Vista_Principal();
                programa.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDialog adDialog;
    private javax.swing.JButton btnCrearCancelar;
    private javax.swing.JButton btnCrearUser;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JDialog crearAccDialog;
    private javax.swing.JButton createAccBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton ingresosBtn;
    private javax.swing.JMenuItem ingresosMenuItem;
    private javax.swing.JButton initBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JLabel mainlabel;
    private javax.swing.JButton medicosBtn;
    private javax.swing.JMenuItem medicosMenuItem;
    private javax.swing.JMenu openMenu;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JButton pacientesBtn;
    private javax.swing.JMenuItem pacientesMenuItem;
    private javax.swing.JPanel panelTools;
    private javax.swing.JLabel passLabel;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JDialog sesionDialog;
    private javax.swing.JMenuItem sesionMenuItem;
    private javax.swing.JButton statusBtn;
    private javax.swing.JTextField txtCrearPass;
    private javax.swing.JTextField txtCrearUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userLbl;
    private javax.swing.JMenuItem usersMenuItem;
    // End of variables declaration//GEN-END:variables
}
